_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True
  WEIGHTS: "/WAVE/users2/unix/jkou/PoseTrack/fast-reid/fastreid/config/duke_agw_R101-ibn.pth"


DATASETS:
  NAMES: ("AIC24",)
  TESTS: ("AIC24",)

OUTPUT_DIR:  logs/jk_experiments/agw-R101-ibn
